version: "3.8"
services:
  server:
    environment:
      MYSQL_ROOT_PASSWORD: passW0@d
      LANG: ja_JP.UTF-8
    image: mysql
    volumes:
      - ./server_conf.d:/etc/mysql/conf.d
      - ./initdb.d:/docker-entrypoint-initdb.d
  client:
    depends_on:
      - server
    environment:
      LANG: ja_JP.UTF-8
    image: mysql
    volumes:
      - ./client_conf.d:/etc/mysql/conf.d
    working_dir: /workspace
